
name: inception

services:
  nginx:
    container_name: nginx-cont
    restart: on-failure
    build:
      context: ./requirements/nginx/.
      args:
        - CERT_FOLDER
        - CERTIFICATE
        - KEY
        - COUNTRY
        - STATE
        - LOCALITY
        - ORGANIZATION
        - UNIT
        - COMMON_NAME
    depends_on: 
      - wordpress
    networks:
      - inception
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - wordpress_vol:/var/www/html

  wordpress:
    container_name: wordpress-cont
    build: ./requirements/wordpress/.
    restart: on-failure
    depends_on: 
      - mariadb
    networks:
      - inception
    expose:
      - "9000"
    volumes:
      - wordpress_vol:/var/www/html
    env_file:
      - .env

  mariadb:
    container_name: mariadb-cont
    build: ./requirements/mariadb/.
    restart: on-failure
    networks:
      - inception
    expose:
      - "3306"
    volumes:
      - mariadb_vol:/var/lib/mysql
    env_file:
      - .env

volumes:
  wordpress_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ngordobi/data/wordpress
  mariadb_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ngordobi/data/mariadb

networks:
  inception:
    driver: bridge

